#!/bin/bash
# Run garuda hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    if [ -z "$(grep "^DISTRIB_CODENAME=" $file)" ] ; then
        # add missing DISTRIB_CODENAME=
        echo "DISTRIB_CODENAME=rolling" >> $file
    fi
    sed -i /etc/lsb-release \
        -e 's,DISTRIB_ID=.*,DISTRIB_ID=ArcticOS,' \
        -e 's,DISTRIB_RELEASE=.*,DISTRIB_RELEASE=21.11,' \
        -e 's,DISTRIB_CODENAME=.*,DISTRIB_CODENAME=ArcticOS,' \
        -e 's,DISTRIB_DESCRIPTION=.*,DISTRIB_DESCRIPTION=\"ArcticOS\",'
}

Os_release() {
    local file=/usr/lib/os-release
    
    sed -i /usr/lib/os-release \
        -e 's,NAME=.*,NAME=\"ArcticOS\",' \
        -e 's,PRETTY_NAME=.*,PRETTY_NAME=\"ArcticOS\",' \
        -e 's,ID=.*,ID=garuda,' \
        -e 's,ID_LIKE=.*,ID_LIKE=arch,' \
        -e 's,BUILD_ID=.*,BUILD_ID=rolling,' \
        -e 's,HOME_URL=.*,HOME_URL=\"https://github.com/arctic-os/\",' \
        -e 's,DOCUMENTATION_URL=.*,DOCUMENTATION_URL=\"https://github.com/arctic-os/\",' \
        -e 's,SUPPORT_URL=.*,SUPPORT_URL=\"https://github.com/arctic-os/\",' \
        -e 's,BUG_REPORT_URL=.*,BUG_REPORT_URL=\"https://github.com/arctic-os/\",' \
        -e 's,LOGO=.*,LOGO=arcticlinux,'
        
    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi

    sed -i 's|Arch|ArcticOS|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     ;;
    esac
}

Main "$@"
 

